# Generated by Django 2.2.5 on 2020-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ManyToManyField(to='rooms.RoomType'),
        ),
    ]
